# Generated by Django 4.1.2 on 2022-10-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "hospital_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "country_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("polit", models.CharField(max_length=255)),
                ("sensor", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("comments", models.CharField(blank=True, default="", max_length=100)),
                ("data", models.TextField(blank=True, default="")),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "annotation",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("polit", models.CharField(max_length=255)),
            ],
        ),
    ]
